# Generated by Django 6.0.2 on 2026-02-22 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('reg_no', models.CharField(max_length=50, unique=True)),
                ('department', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='student_images/')),
                ('face_encoding', models.TextField(blank=True, help_text='JSON representation of numpy array', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
